import { contextBridge, ipcRenderer, webUtils } from 'electron'
import type {
  AppSettingsUpdate,
  AttachmentKind,
  ExportOptions,
  InvoiceManagerApi,
  Project,
  SettingsDirectoryKind,
} from '../src/shared/models'

const IPC_CHANNELS = {
  getSettings: 'settings:get',
  saveSettings: 'settings:save',
  createProject: 'project:create',
  openProject: 'project:open',
  openRecentProject: 'project:open-recent',
  closeCurrentProject: 'project:close-current',
  checkRecentProject: 'project:check-recent',
  removeRecentProject: 'project:remove-recent',
  saveProject: 'project:save',
  importAttachments: 'attachment:import',
  importDroppedAttachments: 'attachment:import-dropped',
  readAttachmentForOcr: 'attachment:read-for-ocr',
  readAttachmentPreview: 'attachment:read-preview',
  openAttachment: 'attachment:open',
  revealProject: 'project:reveal',
  exportProject: 'project:export',
  deleteCurrentProject: 'project:delete-current',
  getAllProjectsSummary: 'project:summary-all',
  moveCurrentProject: 'project:move-current',
  getPayerUsage: 'settings:payer-usage',
  chooseSettingsDirectory: 'settings:choose-directory',
  checkSettingsDirectories: 'settings:check-directories',
  getRecentProjectStatuses: 'settings:recent-project-statuses',
  removeInvalidRecentProjects: 'settings:remove-invalid-projects',
  relocateRecentProject: 'settings:relocate-project',
  getAppDiagnostics: 'app:diagnostics',
  openAppDataDirectory: 'app:open-data-directory',
} as const

const api: InvoiceManagerApi = {
  getSettings: () => ipcRenderer.invoke(IPC_CHANNELS.getSettings),
  saveSettings: (settings: AppSettingsUpdate) => ipcRenderer.invoke(IPC_CHANNELS.saveSettings, settings),
  createProject: (name: string) => ipcRenderer.invoke(IPC_CHANNELS.createProject, name),
  openProject: () => ipcRenderer.invoke(IPC_CHANNELS.openProject),
  openRecentProject: (rootPath: string) => ipcRenderer.invoke(IPC_CHANNELS.openRecentProject, rootPath),
  closeCurrentProject: () => ipcRenderer.invoke(IPC_CHANNELS.closeCurrentProject),
  checkRecentProject: (rootPath: string) => ipcRenderer.invoke(IPC_CHANNELS.checkRecentProject, rootPath),
  removeRecentProject: (rootPath: string) => ipcRenderer.invoke(IPC_CHANNELS.removeRecentProject, rootPath),
  saveProject: (project: Project) => ipcRenderer.invoke(IPC_CHANNELS.saveProject, project),
  importAttachments: (kind: AttachmentKind) => ipcRenderer.invoke(IPC_CHANNELS.importAttachments, kind),
  importDroppedAttachments: (kind: AttachmentKind, files: File[]) => ipcRenderer.invoke(
    IPC_CHANNELS.importDroppedAttachments,
    kind,
    files.map((file) => webUtils.getPathForFile(file)).filter(Boolean),
  ),
  readAttachmentForOcr: (attachmentId: string) => ipcRenderer.invoke(IPC_CHANNELS.readAttachmentForOcr, attachmentId),
  readAttachmentPreview: (attachmentId: string) => ipcRenderer.invoke(IPC_CHANNELS.readAttachmentPreview, attachmentId),
  openAttachment: (attachmentId: string) => ipcRenderer.invoke(IPC_CHANNELS.openAttachment, attachmentId),
  revealProject: () => ipcRenderer.invoke(IPC_CHANNELS.revealProject),
  exportProject: (project: Project, options: ExportOptions) => ipcRenderer.invoke(IPC_CHANNELS.exportProject, project, options),
  deleteCurrentProject: () => ipcRenderer.invoke(IPC_CHANNELS.deleteCurrentProject),
  getAllProjectsSummary: (currentProject?: Project) => ipcRenderer.invoke(IPC_CHANNELS.getAllProjectsSummary, currentProject),
  moveCurrentProject: () => ipcRenderer.invoke(IPC_CHANNELS.moveCurrentProject),
  getPayerUsage: () => ipcRenderer.invoke(IPC_CHANNELS.getPayerUsage),
  chooseSettingsDirectory: (kind: SettingsDirectoryKind) => ipcRenderer.invoke(IPC_CHANNELS.chooseSettingsDirectory, kind),
  checkSettingsDirectories: () => ipcRenderer.invoke(IPC_CHANNELS.checkSettingsDirectories),
  getRecentProjectStatuses: () => ipcRenderer.invoke(IPC_CHANNELS.getRecentProjectStatuses),
  removeInvalidRecentProjects: () => ipcRenderer.invoke(IPC_CHANNELS.removeInvalidRecentProjects),
  relocateRecentProject: (oldRootPath: string) => ipcRenderer.invoke(IPC_CHANNELS.relocateRecentProject, oldRootPath),
  getAppDiagnostics: () => ipcRenderer.invoke(IPC_CHANNELS.getAppDiagnostics),
  openAppDataDirectory: () => ipcRenderer.invoke(IPC_CHANNELS.openAppDataDirectory),
}

contextBridge.exposeInMainWorld('invoiceManager', api)
